name: grafana-otel

services:
  lgtm:
    image: "grafana/otel-lgtm:latest"
    container_name: lgtm
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # GRPC
      - "4318:4318" # HTTP
    volumes:
      - grafana-storage:/var/lib/grafana
      - prometheus-storage:/etc/prometheus
      - loki-storage:/loki
      - tempo-storage:/var/tempo

networks:
  default:
    name: lgtm
    driver: bridge

volumes:
  grafana-storage:
  prometheus-storage:
  loki-storage:
  tempo-storage:
